### ISSUE TITLE
Overlay size

### ISSUE THREAD

**Issue by lordfuoco** [unicef-polymer/etools-loading#1]
When the overlay is enabled it does not cover the full height of a page with scrollbars, thus is possible to scroll or even not see at all the overlay if the user trigger it being 'scrolled down'

**Comment by lordfuoco** [comment]
![etools-loading-error](https://cloud.githubusercontent.com/assets/5890166/21009205/b277340c-bd45-11e6-955c-e1bdba7fb575.png)

**Comment by adi130987** [comment]
#2

**Comment by adi130987** [comment]
Closing issue ... fixed in PR #2.
